# for_debug
FOR_DEBUG: True        # Ture or False

MANUAL_SEED: 123
TRAIN_GPU:
  - 0

DATA_TYPE: "baseline"   # baseline or refine

model_type: "pointnet_vlad"
use_patch_recon: False
use_patch_feature_contrast: False
use_hard_negative_patch_mining: False
weight_place_recognition: 1.0
weight_patch_recon: 0.25
weight_patch_feature_contrast: 0.25

ARCH: "pptnet"
GLOBAL_FEAT: True
FEATURE_TRANSFORM: True
MAX_POOL: False
GROUP: 8

AGGREGATION: 'spvlad'
LAST_NORMALIZATION: False
NUM_POINTS: 4096

FEATURE_OUTPUT_DIM: 256

EXP_DIR: /home/ericxhzou/Code/ppt-net-plus/exp

# TRAIN
TRAIN_BATCH_SIZE: 2
TRAIN_POSITIVES_PER_QUERY: 2
TRAIN_NEGATIVES_PER_QUERY: 18

DECAY_STEP: 200000
DECAY_RATE: 0.7

# BASE_LEARNING_RATE: 0.00001
BASE_LEARNING_RATE: 0.000005
MOMENTUM: 0.9
OPTIMIZER: 'adam'
MAX_EPOCH: 20

LEARNING_RATE_DECAY: 'step'

# the margin is too small
MARGIN_1: 0.5
MARGIN_2: 0.2

BN_INIT_DECAY: 0.5
BN_DECAY_DECAY_RATE: 0.5
BN_DECAY_CLIP: 0.99

TRAIN_FILE_ROOT: '/test/work2020/pointnetvlad/generating_queries/pickle_data'
TEST_FILE_ROOT: '/test/work2020/pointnetvlad/generating_queries/pickle_data'

# LOSS
LOSS_FUNCTION: 'quadruplet'
LOSS_LAZY: True
TRIPLET_USE_BEST_POSITIVES: False
LOSS_IGNORE_ZERO_BATCH: False

# EVAL6
EVAL_BATCH_SIZE: 2
EVAL_POSITIVES_PER_QUERY: 4
EVAL_NEGATIVES_PER_QUERY: 12

#  ----------- switch data for evaluation ----------
# WHU Data: hankou, campus
# Oxford RobotCar: oxford
# 3-Inhouse: university, residential, business
dataset: 'oxford'